export default function createForm() {
    const form = document.createElement('form')
    form.setAttribute('method', 'post')
    //form.setAttribute('action', 'something')
    const name = document.createElement('input')
    name.setAttribute('type', 'text')
    name.setAttribute('name', 'name')
    name.setAttribute('placeholder', 'Your full name')
    const title = document.createElement('input')
    title.setAttribute('type', 'text')
    title.setAttribute('placeholder', 'Your title of announcement')
    title.setAttribute('name', 'title')
    const message = document.createElement('textarea')
    message.setAttribute('placeholder', 'text here')
    const submit = document.createElement('input')
    submit.setAttribute('type', 'submit')
    submit.setAttribute('value', 'Submit')
    form.appendChild(name)
    form.appendChild(title)
    form.appendChild(message)
    form.appendChild(submit)
    console.log('xd')
    return form
}